spring:
  datasource:
  #    url: jdbc:mysql://${MYSQL}/dm_cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    #    driver-class-name: com.mysql.jdbc.Driver
    #    username: dm
    #    password: ${MYSQL_PASSWORD :ENC(kWGtsTQceU2EmQSvMakMJg==)}
    url: jdbc:mysql://100.76.7.167:3306/plan?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      max-lifetime: 500000
    dbcp2:
      initial-size: 5
      max-total: 10
      min-idle: 3
      max-idle: 6
      max-wait-millis: 10000
      test-on-borrow: false
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  jwt:
    header: Authorization
    secret: iot.technology
  origin: http://172.31.244.178:8081
